# GEMINI_API_KEY, OPENAI_API_KEY
"""
app/ai/config.py
────────────────
AI 모듈 설정 상수.
"""

# Gemini 모델 기본 파라미터
GEMINI_DEFAULT_TEMPERATURE = 0.7
GEMINI_DEFAULT_MAX_OUTPUT_TOKENS = 2048
GEMINI_DEFAULT_TOP_P = 0.95

# OpenAI 모델 기본 파라미터
OPENAI_DEFAULT_TEMPERATURE = 0.7
OPENAI_DEFAULT_MAX_TOKENS = 2048

# 재시도 설정
AI_MAX_RETRIES = 2
AI_RETRY_DELAY_SECONDS = 1.0
